app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//API validation routes no login required
Route::get('/validate_site_json', 'OapiController@validate_site_json');
Route::get('/validate_update_json', 'OapiController@validate_update_json');

//Dashboard routes
Route::get("/my_subscriptions","DashboardController@my_subscriptions");
Route::get("/my_plans","DashboardController@my_plans");
Route::get("/create_site","DashboardController@create_site");
Route::get("/my_sites","DashboardController@my_sites");
Route::get("/my_servers","DashboardController@my_servers");


Route::post("/create_linode","DashboardController@create_linode");
Route::post("/create_websitebar","DashboardController@create_websitebar");
Route::post("/delete_websitebar","DashboardController@delete_websitebar");
Route::post("/create_api_key","DashboardController@create_api_key");
Route::get('/logout', 'DashboardController@logout');
Route::post("/set_lang","DashboardController@set_lang");
Route::get("/addons","DashboardController@addons");
Route::get("/backups","DashboardController@backups");
Route::get("/restore","DashboardController@restore");
Route::get("/my_domains","DashboardController@my_domains");
Route::post("/publish_website","DashboardController@publish_website");
Route::post("/get_barserver_info","DashboardController@get_barserver_info");
Route::get("/save_barsite_from_pete","DashboardController@save_barsite_from_pete");
Route::get("/show_wp_pass","DashboardController@show_wp_pass");
Route::get("/check_websitebar_subdomain","DashboardController@check_websitebar_subdomain");
Route::get("/testui","DashboardController@testui");
Route::get("/save_barsite","DashboardController@save_barsite");

Route::get("/get_domains","DashboardController@get_domains");
Route::get("/shut_down","DashboardController@shut_down");
Route::get("/boot","DashboardController@boot");
Route::get("/reboot","DashboardController@reboot");

Route::get("/clone_barsite","DashboardController@clone_barsite");
Route::get("/delete_barsite","DashboardController@delete_barsite");
Route::get("/restore_barsite","DashboardController@restore_barsite");
Route::get("/destroy_barsite","DashboardController@destroy_barsite");
Route::get("/continue_barsite","DashboardController@continue_barsite");
Route::get("/suspend_barsite","DashboardController@suspend_barsite");
Route::get("/restore_barsite_from_backup","DashboardController@restore_barsite_from_backup");
Route::get("/publish_barsite","DashboardController@publish_barsite");
Route::get("/create_barsite","DashboardController@create_barsite");
Route::get("/my_addons","DashboardController@my_addons");

/////OMISSIONS ROUTES///////////

Route::get("/set_omission","OmissionsController@set_omission");
Route::get("/edit/{id}","OmissionsController@edit");
Route::post('/answer_test', 'OmissionsController@answer_test');
Route::post('/mission_submitted', 'OmissionsController@mission_submitted');
Route::post('/wp_select_user', 'OmissionsController@wp_select_user');
Route::post('/save_omission_file', 'OmissionsController@save_omission_file');
Route::post('/save_brief', 'OmissionsController@save_brief');
Route::get("/send_notification_test/{id}","OmissionsController@send_notification_test");

/////END OMISSIONS ROUTES///////

//Contributor routes
Route::get('/select_customer', 'ContributorsController@select_customer');

//Admin routes
Route::get('/open_tickets', 'AdminController@open_tickets');
Route::get('/customers', 'AdminController@customers');
Route::get('/get_customer/{id}', 'AdminController@get_customer');
Route::get('/test_email', 'AdminController@test_email');

//Otickets routes
Route::resource("otickets","OticketController");
Route::post("store_answer","OticketController@store_answer");
Route::post("update_status","OticketController@update_status");
Route::get("all_tickets","OticketController@all");

//Options routes
Route::resource("wp_global_options","WpGlobalOptionController");
Route::resource("barthemes","BarthemeController");
Route::resource("barrecords","BarrecordController");

Route::resource("bardomains","BardomainController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::get("/create_record","BardomainController@create_record");
Route::post("/store_record","BardomainController@store_record");
Route::post("/delete_record","BardomainController@delete_record");


Route::get('/', array('as' => 'dashboard.create_site', 'uses' => 'DashboardController@create_site'));

app/Http/Controllers/OmissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use View;
use App\DashboardOption;
use Illuminate\Support\Facades\Auth;
use App;
use Log;
use App\Wp_omission;
use App\Wp_ostate;
use App\Wp_omissions_state;
use App\Wp_omissionmeta;
use App\Wp_omissions_todo;
use App\Bardomain;
use App\Pete;
use App\User;
use DB;
use Input;
use Illuminate\Support\Facades\Redirect;

class OmissionsController extends Controller
{
	
  public function __construct()
  {
	  
	if(isset($_GET["email_token"])){

	  include_once(env('WP_LOAD_PATH')."/wp-load.php"); 
	  
	  $token = $_GET['email_token'];
	  $user = User::where('email_token',$token)->first();
	  Log::info('Tiene token');	
	  if($user){
		 Log::info("Encontro el usuario: $user->ID");	
		 Log::info("Entra al constructor");
	  	 wp_set_auth_cookie( $user->ID );
		 Auth::loginUsingId($user->ID);
		 
	  }else{
	  	$this->middleware('auth.wp');	
	  }
	}else{
		$this->middleware('auth.wp');	
	}
	  	
  }
  
  
public function set_omission(){
	
	$viewsw = "my_addons";
	$order_id = Input::get('order_id');
	$order_item_id = Input::get('order_item_id');
	$user_id = Input::get('user_id');
	$product_id = Input::get('product_id');
	
	$wp_omission = Wp_omission::where('user_id', $user_id)->where("order_id",$order_id)->where("order_item_id",$order_item_id)->where("product_id",$product_id)->first();
	
	if(!isset($wp_omission)){
		
		Log::info("No existe");
		$wp_omission = new Wp_omission();
		$wp_omission->order_id = $order_id;
		$wp_omission->order_item_id = $order_item_id;
		$wp_omission->user_id = $user_id;
		$wp_omission->product_id = $product_id;
		$wp_omission->save();
	}
	
	//return redirect()->action('DashboardController@edit_addon', ['id' => $wp_omission->id]);
	return redirect('/edit'."/$wp_omission->id");
	
}
  
public function edit($id){
	
	$wp_omission = Wp_omission::findOrFail($id);
	
	//////SHARED HTML VARIABLES///
    $current_user = Auth::user();			
    $wordpress_url = env('WP_URL');
    $dashboard_option = new DashboardOption();
	$role = getUserRole($current_user->ID);
	if($current_user->dashboard_lang){
		$global_lang = $current_user->dashboard_lang;
		App::setLocale($current_user->dashboard_lang);
	}else{
		$global_lang = "en";
		App::setLocale("en");
	}
	//////////////////////////
	
	$viewsw = "my_addons";
	
	//HACK FOR ADMIN
	$user = $current_user;
	if(($role == "administrator") || ($role =="contributor")){
		
		$admin = true;
		$viewsw = "select_customer";
		$user =  User::findOrFail($wp_omission->user_id);
		
		if($user->dashboard_lang){
			$global_lang = $user->dashboard_lang;
			App::setLocale($user->dashboard_lang);
		}
			
	}
	//////////////

	//OBTENER TODOS LOS META VALUES DEL BRIEF
	$omissionmeta = $wp_omission->get_metas();
	
	//OBTENER TODOS LOS ARCHIVOS DEL BRIEF
	$files = DB::select("select * from wp_omissions_files where omission_id = {$wp_omission->id}");
	
	$product_origin_id =icl_object_id($wp_omission->product_id, 'product', false);
	$product = get_product($product_origin_id);
	
	//OBTENER TODS LOS CAMPOS DEL BRIEF PARA ESTE PRODUCTO		
	$rows = Wp_omission::get_product_fields($product_origin_id);
	
	//OBETENER EL ESTADO SELECCIONADO
	
	if($product->get_title() == "Premium Branding Package"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view',"branding_kit")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"branding_kit");
		$todos = $selected_state->get_todos();
		
		return view('omissions.branding_kit',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','product_owner','todos'));
		
	}else if($product->get_title() == "8-hr Designer Package"){
		$product_owner =  User::findOrFail($wp_omission->user_id);
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view', "hr_design")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"hr_design");
		$todos = $selected_state->get_todos();
		
		
		if(isset($wp_omission->hr_package_webtender_selected_id)){
			$webtender = User::findOrFail($wp_omission->hr_package_webtender_selected_id);
		}
		return view('omissions.hr_design',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','webtender','product_owner','todos'));
		
	}else if($product->get_title() == "8-hr Web Developer Package"){
		$product_owner =  User::findOrFail($wp_omission->user_id);
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view', "hr_development")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"hr_development");
		$todos = $selected_state->get_todos();
		
		if(isset($wp_omission->hr_package_webtender_selected_id)){
			$webtender = User::findOrFail($wp_omission->hr_package_webtender_selected_id);
		}
		
		return view('omissions.hr_development',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','webtender','product_owner','todos'));
		
	}else if($product->get_title() == "Social Media Branding Kit"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view', "social_media_kit")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"social_media_kit");
		$todos = $selected_state->get_todos();
		
		return view('omissions.social_media_kit',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','todos'));
		
	}else if($product->get_title() == "SSl Certificate"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view', "ssl_certificate")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"ssl_certificate");
		$todos = $selected_state->get_todos();
		$select_options_array = Bardomain::orderBy('created_at', 'asc')->where('user_id', $user->ID)->get();
		
		return view('omissions.ssl_certificate',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','select_options_array','todos'));
	}else if($product->get_title() == "Web Package with Hours of Design, Content and Web Development"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view',"web_package")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"web_package");
		$todos = $selected_state->get_todos();
		
		return view('omissions.web_package',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','product_owner','todos'));
		
	}else if($product->get_title() == "SSl Certificate"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view', "ssl_certificate")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"ssl_certificate");
		$todos = $selected_state->get_todos();
		$select_options_array = Bardomain::orderBy('created_at', 'asc')->where('user_id', $user->ID)->get();
		
		return view('omissions.ssl_certificate',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','select_options_array','todos'));
		
	}else if($product->get_title() == "Email Accounts"){
		
		//OBTENER ESTADOS
		$states = Wp_ostate::orderBy('order', 'asc')->where('view',"emails")->get();
		$selected_state = Wp_omissions_state::get_state($wp_omission,"emails");
		$todos = $selected_state->get_todos();
		$select_options_array = Bardomain::orderBy('created_at', 'asc')->where('user_id', $user->ID)->get();
		
		return view('omissions.emails',compact('viewsw','rows','omissionmeta','files','wp_omission','product','current_user','wordpress_url','dashboard_option','role','global_lang','states','selected_state','user','admin','product_owner','select_options_array','todos'));
		
		
		
		
	}
	
}

public function answer_test(){
	
	$current_user = Auth::user();
	if($current_user->dashboard_lang){
		App::setLocale($current_user->dashboard_lang);
	}else{
		App::setLocale("en");
	}
	
	$wp_omission = Wp_omission::findOrFail(input::get('omission_id'));
	
	$sw = true;
	$row_error = "";
	$wp_omission->pc_rows_error = "";
	
	if(input::get('pc_bohemian_value')){
		//A
		$value = input::get('pc_bohemian_value');
		$wp_omission->pc_bohemian_value = (int) $value;
		
	}else{
		$wp_omission->pc_rows_error .= "0,";
		$sw = false;
	}
	if(input::get('pc_outdoorsy_value')){
		//B
		$value = input::get('pc_outdoorsy_value');
		$wp_omission->pc_outdoorsy_value = (int) $value;
	}else{
		$wp_omission->pc_rows_error .= "1,";
		$sw = false;
	}
	if(input::get('pc_informal_value')){
		//C
		$value = input::get('pc_informal_value');
		$wp_omission->pc_informal_value = (int) $value;
		
		
	}else{
		$wp_omission->pc_rows_error .= "2,";
		$sw = false;
	}
	if(input::get('pc_laid_back_value')){
		//D
		$value = input::get('pc_laid_back_value');
		$wp_omission->pc_laid_back_value = (int) $value;
		
		
	}else{
		$wp_omission->pc_rows_error .= "3,";
		$sw = false;
	}
	if(input::get('pc_subtle_value')){
		//E
		$value = input::get('pc_subtle_value');
		$wp_omission->pc_subtle_value = (int) $value;
		
		
	}else{
		$wp_omission->pc_rows_error .= "4,";
		$sw = false;
	}
	if(input::get('pc_delicate_value')){
		//F
		$value = input::get('pc_delicate_value');
		$wp_omission->pc_delicate_value = (int) $value;
		
		
	}else{
		$wp_omission->pc_rows_error .= "5,";
		$sw = false;
	}

resources/views/omissions/partials/_agreement_es.blade.php
<?php

if(isset($webtender)){
	$first_name = strtoupper(get_user_meta( $webtender->ID, "first_name", true )); 
	$last_name = strtoupper(get_user_meta( $webtender->ID, "last_name", true )); 
}

if(isset($product_owner)){
	$owner_first_name = strtoupper(get_user_meta( $product_owner->ID, "first_name", true )); 
	$owner_last_name = strtoupper(get_user_meta( $product_owner->ID, "last_name", true )); 
}

?>

<p>
	Entre los suscritos a saber <strong>{{$owner_first_name}} {{$owner_last_name}}</strong>, quien en adelante se denominará EL CONTRATANTE, de una parte y, de la otra <strong>{{$first_name}} {{$last_name}}</strong>, mayor de edad, de quien en adelante se denominará EL CONTRATISTA, han convenido en celebrar el presente contrato de obra por encargo, sujeto a las siguientes clausulas:<br /> <br />
	
	PRIMERA - OBJETO: En virtud del presente contrato, EL CONTRATANTE, encarga a EL CONTRATISTA la realización de la obra denominada: <strong>{{strtoupper(get_the_title( icl_object_id( $product->id, 'product', false, $global_lang ) ))}}.</strong> <br /><br />
	
	SEGUNDA - OBLIGACIONES DE LAS PARTES: EL CONTRATANTE se compromete a:  Proporcionar a EL CONTRATISTA toda la información básica para la ejecución del trabajo, que será disponible, fiable, correcta, actualizada y completa. <br /><br />

	TERCERA - LISTA DE ENTREGBLES: a continuación se definira la lista de entregables, esta debe ser definida por mutuo acuerdo en una videoconferencia de 30 minutos con el creativo previamente seleccionado y el  cliente. <br />

</p>
 	@include('omissions/partials/_fields', array('ids' => $fields))	
<p>

	
	CUARTA - CESIÓN DE LA(S) OBRA(S) OBJETO DEL CONTRATO: EL CONTRATISTA cede en exclusiva EL CONTRATANTE, la obra denominada: <strong>{{strtoupper(get_the_title( icl_object_id( $product->id, 'product', false, $global_lang ) ))}}</strong> que mediante este contrato se le encargaron y por ello, EL CONTRATISTA no podrá ceder a terceros ninguno de los derechos ni obligaciones establecidas en el presente contrato, salvo autorización expresa y por escrito de EL CONTRATANTE. La cesión de estos derechos se extiende a nivel mundial y durará hasta que la citada obra pase al dominio público. <br /> <br />
	
	QUINTA - DURACIÓN Y ENTREGA DE LA(S) OBRA(S): La entrega de la(s) obra(s) creadas en desarrollo del presente contrato, se llevará a cabo dentro de un plazo de (7) días habiles contados a partir de aceptacion de los terminos de este mismo acuerdo. <br /> <br />
	
	SEXTA - CALIDAD DE LA OBRA: El contratante se compromete a realizar una obra de calidad.<br /> <br />
	
	SEPTIMA - PROPIEDAD INTELECTUAL: Como consecuencia de la cesión de los derechos patrimoniales de EL CONTRATISTA a EL CONTRATANTE, la titularidad de dichos derechos patrimoniales de la obra contratada le corresponde en exclusividad al CONTRATANTE.<br /> <br />
	
	OCTAVA - CONFIDENCIALIDAD: Las partes se comprometen, con carácter mutuo y recíproco, a tratar como “confidencial” toda la información técnica, comercial o de cualquier otra naturaleza comprendida y/o que se derive directa o indirectamente de las indicaciones que la contraparte le haya facilitado para el desarrollo del objeto del presente contrato (en adelante “la información confidencial”). En consecuencia ninguna parte podrá revelar total o parcialmente, de palabra, por escrito o de cualquier otra forma, a ninguna persona física o jurídica, ya sea de carácter público o privado, la Información Confidencial, sin el consentimiento expreso y por escrito de la contraparte. La misma confidencialidad que se imponen a las partes o a terceros que intervengan en la ejecución, deberá ser impuesta por cada una de las partes a sus trabajadores (por cuenta propia o ajena, con relación laboral o mercantil) que de modo directo o indirecto están relacionados con el objeto del contrato. Será obligación de las mismas partes hacer firmar a sus trabajadores un documento vinculante por el que adquieren tal obligación. Este compromiso de confidencialidad, tanto entre las partes como de éstas con sus trabajadores y contratistas, permanecerá durante la vigencia del presente contrato así como un año después de la finalización del mismo.
	<br /> <br />
	 NOVENA - JURISDICCIÓN: Cualquier disputa o 
	diferencia que surja con ocasión del objeto y obligaciones de este contrato serán arregladas en lo posible mediante la negociación y la conciliación entre las partes, para lo cual Website Bar nombrara a una tercera persona encargada de hacer una auditoria para establecer el monto del dinero que deba devolverse en caso de que exista un incumplimiento por parte DEL CONTRATANTE se estipulara el valor de devolución del dinero que en ningun caso podrá ser mayor al 100% del valor pagado por el CONTRATANTE.

<br /> <br />

	@include('omissions/partials/_fields', array('ids' => $approvals))
	
</p>

resources/views/omissions/partials/_how_does_it_work_branding_kit_en.blade.php
<div class="row">
	<div class="col-md-12">
		
		<h3>HOW DOES THE PROCESS WORK?</h3>
		<p>The entire process can take between 3 and 4 weeks, depending on how long it takes you to complete the rounds and revision approvals:</p>
		
		<ol>
			<li>After the purchase has been made, we will send you a link where you can answer a series of questions that will help us learn more about your brand.</li>
			<li>Once we get your answers, we will conduct research and create two brand concepts in a period of 10 days.</li>
			<li>We will then email a round of brand concepts for your review. We’ll also schedule a 30-minute feedback call with our Senior Branding Consultant (Laura Busche).</li>
			<li>Within 7 days we will incorporate your feedback and email a final package with all the assets included in your brand kit.</li>
		</ol> 
		
	</div>
</div>

resources/views/omissions/partials/_how_does_it_work_branding_kit_es.blade.php
<div class="row">
	<div class="col-md-12">
		
		<h3>¿CÓMO FUNCIONA EL PROCESO?</h3>
		<p>El proceso completo puede demorar entre 3 y 4 semanas, dependiendo de cuánto tiempo te tome completar las rondas y aprobaciones de revisión:</p>
		
		<ol>
			<li>Después de que la compra se haya realizado, te enviaremos un link donde podrás respondernos una serie de preguntas que nos ayudarán a conocer más sobre tu marca. </li>
			<li>Una vez que obtengamos tus respuestas, realizaremos una investigación y crearemos dos conceptos de marca en un tiempo de 10 días.</li>
			<li>Después de esto enviaremos un link con los conceptos de marca a tu correo electrónico para revisión y agendamos una videoconferencia de retroalimentación contigo y nuestra consultora en branding Laura Busche de 30 minutos.</li>
			<li>En un tiempo de 7 días incorporaremos los cambios de la retroalimentación y te enviaremos un paquete a tu correo con todos los archivos del kit de marca.</li>
		</ol> 
		
	</div>
</div>

resources/views/omissions/partials/_how_does_it_work_emails_es.blade.php
<div class="row">
	<div class="col-md-12">
		
		<h3>¿CÓMO FUNCIONA EL PROCESO?</h3>
		<p>El proceso completo puede demorar hasta 72 horas, dependiendo de cuánto tiempo te tome completar las preguntas del brief:</p>
		
		<ol>
			<li>Después de que la compra se haya realizado, te enviaremos un link donde donde podrás respondernos una serie de preguntas que nos ayudarán a configurar tus correos electrónicos. </li>
			<li>En un tiempo máximo de 72 horas días deberá estar lista la configuración de tus correos electrónicos.</li>
			
			
		</ol> 
		
	</div>
</div>

resources/views/omissions/partials/_how_does_it_work_hr_designer_es.blade.php
<div class="row">
	<div class="col-md-12">
		
		<h3>¿CÓMO FUNCIONA EL PROCESO?</h3>
		<p>El proceso completo puede demorar entre 1 y 2 semanas, dependiendo de cuánto tiempo te tome completar las rondas y aprobaciones de revisión:</p>
		
		<ol>
			<li>Escoge a un diseñador.</li>
			<li>Una vez hayas escogido a alguno de los diseñadores, este te contactara de vuelta vía correo electrónico o telefonica para agendar una videoconferencia con el.</li> 
			<li>En esta reunión se deberá definir la lista de entregables correspondientes al paquete de las horas que hayas comprado, estos deben quedar consignados en el campo de texto: Lista de entregables y posteriormente firmar el acuerdo de manera digital.</li>
			<li>En un tiempo máximo de 7 días deberán estar listos todos los entregables acordados.</li>
			<li>Si el recibo es a satisfacción se dará por terminado el trabajo.</li>
			
		</ol> 
		
	</div>
</div>

resources/views/omissions/partials/_how_does_it_work_ssl_certicate_es.blade.php
<div class="row">
	<div class="col-md-12">
		
		<h3>¿CÓMO FUNCIONA EL PROCESO?</h3>
		<p>El proceso completo puede demorar hasta 72 horas, dependiendo de cuánto tiempo te tome completar las preguntas del brief</p>
		
		<ol>
			<li>Después de que la compra se haya realizado, te enviaremos un link donde donde podrás respondernos una serie de preguntas que nos ayudarán a configurar el Certificado SSL para tu dominio. </li>
			<li>En un tiempo máximo de 72 horas días estará lista la configuración de tu Certificado SSL.</li>
			
		</ol> 
		
	</div>
</div>

resources/views/omissions/partials/_upload_form.blade.php
<?php
$section = $object->section;
$fnumber = $object->fnumber;

if($global_lang == "es"){
$help_text = $object->help_text_es;
}else if($global_lang == "en"){
$help_text = $object->help_text;
}
?>

<div class="row">
	           <div class="col-md-12" id="displayImages{{$fnumber}}">
				   
				
				   
	  			<label>{{$help_text}}</label>
				<div id="displayImages_{{$section}}">
					@foreach($array as $file)	 
					
					
					
					@if($file->section == $section)
					
					
					
					@if(($file->extension == "png") || ($file->extension == "PNG") || ($file->extension == "jpg") || ($file->extension == "JPG") || ($file->extension == "gif") || ($file->extension == "GIF") || ($file->extension == "jpeg") || ($file->extension == "JPEG"))
		   			
				
		   			
					<div class="img-wrap">
						
					    <span class="close"><a href="/delete_file/{{$file->id}}?current_url={{URL::full()}}" class="delete_file_from_brief" omissions_file_id="{{$file->id}}" omission_id="{{$wp_omission->id}}" form_number="{{$fnumber}}" current_url="{{URL::full()}}" section ="logo">&times;</a></span>
					    <a class="fancybox" href="/files/{{$wp_omission->id}}/{{$file->file}}.{{$file->extension}}" data-fancybox-group="gallery" title="{{$file->title}}"><img src="/files/{{$wp_omission->id}}/{{$file->file}}.thumb.{{$file->extension}}" alt="" /></a>
					</div>
					
					@else
					
					<div class="img-wrap">
					    <span class="close"><a href="/delete_file/{{$file->id}}?current_url={{URL::full()}}" class="delete_file_from_brief" omissions_file_id="{{$file->id}}" omission_id="{{$wp_omission->id}}" form_number="{{$fnumber}}" current_url="{{URL::full()}}" section ="logo">&times;</a></span>
					    <a class="fancybox" href="/files/{{$wp_omission->id}}/{{$file->file}}.{{$file->extension}}" data-fancybox-group="gallery" title="{{$file->title}}"><img src="/file.png" alt="" /></a>
					</div>
					
					@endif
					@endif
					@endforeach
					
				
									
				</div>
				
				<div id="spinner{{$fnumber}}" class="cssload-loader" style="display:none;position:absolute;top:50%;"></div>
	          </div>
	    </div>
		<br />


@if($permissions == "admin")

  @if(($role == "administrator") || ($role == "contributor"))
  

  <div id="upload_brief_area_{{$section}}" class="upload_brief_file">

	  <form action="{{ route('wp_omissions_files.store') }}" method="POST" class="form-horizontal frm-logoUpload" enctype="multipart/form-data">
		  <input type="file" id="Uploadid{{$fnumber}}" name="file" class="Uploadid" section="{{$section}}" multiple>
			
		  <input type="hidden" name="_token" value="{{ csrf_token() }}">
		  <input type="hidden" name="omission_id" value="{{ $wp_omission->id }}">
		  <input type="hidden" name="section" value="{{$section}}">
			
	  </form>

	  <br />
  </div>

  @endif

@else

<div id="upload_brief_area_{{$section}}" class="upload_brief_file">
	<form action="{{ route('wp_omissions_files.store') }}" method="POST" class="form-horizontal frm-logoUpload" enctype="multipart/form-data">
	
		<input type="file" id="Uploadid{{$fnumber}}" name="file" class="Uploadid" section="{{$section}}" multiple>
			
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<input type="hidden" name="omission_id" value="{{ $wp_omission->id }}">
		<input type="hidden" name="section" value="{{$section}}">
			
	</form>

	<br />

</div>

@endif