app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//API validation routes no login required
Route::get('/validate_site_json', 'OapiController@validate_site_json');
Route::get('/validate_update_json', 'OapiController@validate_update_json');

//Dashboard routes
Route::get("/my_subscriptions","DashboardController@my_subscriptions");
Route::get("/my_plans","DashboardController@my_plans");
Route::get("/create_site","DashboardController@create_site");
Route::get("/my_sites","DashboardController@my_sites");
Route::get("/my_servers","DashboardController@my_servers");


Route::post("/create_linode","DashboardController@create_linode");
Route::post("/create_websitebar","DashboardController@create_websitebar");
Route::post("/delete_websitebar","DashboardController@delete_websitebar");
Route::post("/create_api_key","DashboardController@create_api_key");
Route::get('/logout', 'DashboardController@logout');
Route::post("/set_lang","DashboardController@set_lang");
Route::get("/addons","DashboardController@addons");
Route::get("/backups","DashboardController@backups");
Route::get("/restore","DashboardController@restore");
Route::get("/my_domains","DashboardController@my_domains");
Route::post("/publish_website","DashboardController@publish_website");
Route::post("/get_barserver_info","DashboardController@get_barserver_info");
Route::get("/save_barsite_from_pete","DashboardController@save_barsite_from_pete");
Route::get("/show_wp_pass","DashboardController@show_wp_pass");
Route::get("/check_websitebar_subdomain","DashboardController@check_websitebar_subdomain");
Route::get("/testui","DashboardController@testui");
Route::get("/save_barsite","DashboardController@save_barsite");

Route::get("/get_domains","DashboardController@get_domains");
Route::get("/shut_down","DashboardController@shut_down");
Route::get("/boot","DashboardController@boot");
Route::get("/reboot","DashboardController@reboot");

Route::get("/clone_barsite","DashboardController@clone_barsite");
Route::get("/delete_barsite","DashboardController@delete_barsite");
Route::get("/restore_barsite","DashboardController@restore_barsite");
Route::get("/destroy_barsite","DashboardController@destroy_barsite");
Route::get("/continue_barsite","DashboardController@continue_barsite");
Route::get("/suspend_barsite","DashboardController@suspend_barsite");
Route::get("/restore_barsite_from_backup","DashboardController@restore_barsite_from_backup");
Route::get("/publish_barsite","DashboardController@publish_barsite");
Route::get("/create_barsite","DashboardController@create_barsite");
Route::get("/my_addons","DashboardController@my_addons");

/////OMISSIONS ROUTES///////////

Route::get("/set_omission","OmissionsController@set_omission");
Route::get("/edit/{id}","OmissionsController@edit");
Route::post('/answer_test', 'OmissionsController@answer_test');
Route::post('/mission_submitted', 'OmissionsController@mission_submitted');
Route::post('/wp_select_user', 'OmissionsController@wp_select_user');
Route::post('/save_omission_file', 'OmissionsController@save_omission_file');
Route::post('/save_brief', 'OmissionsController@save_brief');
Route::get("/send_notification_test/{id}","OmissionsController@send_notification_test");

/////END OMISSIONS ROUTES///////

//Contributor routes
Route::get('/select_customer', 'ContributorsController@select_customer');

//Admin routes
Route::get('/open_tickets', 'AdminController@open_tickets');
Route::get('/customers', 'AdminController@customers');
Route::get('/get_customer/{id}', 'AdminController@get_customer');
Route::get('/test_email', 'AdminController@test_email');

//Otickets routes
Route::resource("otickets","OticketController");
Route::post("store_answer","OticketController@store_answer");
Route::post("update_status","OticketController@update_status");
Route::get("all_tickets","OticketController@all");

//Options routes
Route::resource("wp_global_options","WpGlobalOptionController");
Route::resource("barthemes","BarthemeController");
Route::resource("barrecords","BarrecordController");

Route::resource("bardomains","BardomainController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::get("/create_record","BardomainController@create_record");
Route::post("/store_record","BardomainController@store_record");
Route::post("/delete_record","BardomainController@delete_record");


Route::get('/', array('as' => 'dashboard.create_site', 'uses' => 'DashboardController@create_site'));

app/Oticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Oticket extends Model
{
    //
	protected $table = 'wp_otickets';

	function randomDigits($length){
	    $numbers = range(0,9);
	    shuffle($numbers);
	    for($i = 0; $i < $length; $i++){
	    	global $digits;
	       	$digits .= $numbers[$i];
	    }
	    return $digits;
	}
}

app/Http/Controllers/OticketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\User;
use App\Site;
use App\Oupdate;
use App\Oanswer;
use App\DashboardOption;
use Input;
use Illuminate\Support\Facades\Auth;
use App\Pete;
use App\Oticket;
use Illuminate\Support\Facades\Redirect;
use DB;
use Mailjet;
use View;
use App;

class OticketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	
	public function __construct()
	{
	     $this->middleware('auth.wp');		
	}
	
    public function all()
    {
		
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$viewsw = "support";
		$user = Auth::user();
		$otickets = Oticket::where("user_id",$user->ID)->orderBy('status', 'desc')->paginate(10);	
		
		return view('otickets.all',compact('viewsw','otickets','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }
	
    public function open_tickets()
    {
		
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$viewsw = "open_tickets";
		$user = Auth::user();
		$otickets = Oticket::where("status","OPEN")->orderBy('status', 'desc')->paginate(20);	
		
		return view('otickets.all',compact('viewsw','otickets','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }
	
    public function index()
    {
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$viewsw = "support";
		$user = Auth::user();
		$open_tickets = Oticket::where("status","OPEN")->where("user_id",$user->ID)->orderBy('created_at', 'desc')->get();
		$closed_tickets = Oticket::where("status","CLOSED")->where("user_id",$user->ID)->orderBy('created_at', 'desc')->get()->take(5);
		
		return view('otickets.index',compact('viewsw','open_tickets','closed_tickets','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
		
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$user = Auth::user();
		$viewsw = "support";
		$sites = Site::where("user_id",$user->ID)->where('domain', '!=' , "")->whereNotNull('domain')->get();
		
		return view('otickets.create',compact('viewsw','sites','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
		$user = Auth::user();
		$ticket = new Oticket();
		$ticket->summary = $request->input("summary");
		$ticket->regarding = $request->input("regarding");
		$ticket->status = "OPEN";
		$ticket->user_id = $user->ID;
		$ticket->opened_by = date('Y-m-d H:i:s');
		$ticket->opened_by_login = $user->user_login;
		$ticket->updated_by = date('Y-m-d H:i:s');
		$ticket->updated_by_login = $user->user_login;
		$oid = $ticket->randomDigits(7);
		$ticket->ticket_id = "{$oid}";
		$ticket->body = $request->input("body");
		$ticket->save();
		
	    $dashboard_option = new DashboardOption();
		$sender_email = $dashboard_option->get_meta_value("sender_email");
		$system_notification_email = $dashboard_option->get_meta_value("system_notification_email");
		
		$params = [
			"method" => "POST",
			"from" => $sender_email,
			"to" => $system_notification_email,
			"subject" => "Importante!! Un suscriptor creo un ticket desde: ".env('WP_URL'),
			"html" => "El usuario". $user->user_email . " creo un ticket desde: ".env('WP_URL')
		];
		
		$result = Mailjet::sendEmail($params);

		if (!Mailjet::getResponseCode() == 200){
			echo "error - ".Mailjet::getResponseCode();
			return $result;
		}
		
		return Redirect::to('/otickets');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$oticket = Oticket::findOrFail($id);
		
		//$oanswers = Oanswer::where("oticket_id",$id)->get();
		$user = Auth::user();
		$oanswers = DB::select("SELECT a.created_at, u.user_login, a.user_id, a.body, a.file FROM wp_oanswers a inner join wp_otickets t on t.id = a.oticket_id inner join wp_users u on a.user_id = u.ID where t.id = {$id} order by a.created_at asc");
		
		$viewsw = "support";
		return view('otickets.show', compact('viewsw','oticket','oanswers','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
	 	$viewsw = "updates";
		$oupdate = Oupdate::findOrFail($id);
		
		return view('oupdates.edit', compact('viewsw','oupdate','current_user','wordpress_url','dashboard_option','role','global_lang'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
		$oupdate = Oupdate::findOrFail($id);
		$oupdate->title = $request->input("title");
		$oupdate->description = $request->input("description");
		$oupdate->branch = $request->input("branch");
		
		$oupdate->save();
		
		return redirect()->route('oupdates.index')->with('message', 'Update created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	public function destroy($id)
	{
		
		
		$oupdate = Oupdate::findOrFail($id);
		$oupdate->delete();
		
		return redirect()->route('oupdates.index')->with('message', 'Deleted successfully.');
		
	}
	
	public function store_answer(Request $request){
		
	    $dashboard_option = new DashboardOption();
		
		$user = Auth::user();
		$oanswer = new Oanswer();
		$oanswer->user_id = $user->ID;
		$oanswer->body = Input::get('body');
		$oanswer->oticket_id = Input::get('oticket_id');
		
		if($request->file('filem')!= ""){
			
			$file = $request->file('filem');
	        // SET UPLOAD PATH
	        $destinationPath = "dashboard_tickets/{$oanswer->oticket_id}";
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$oanswer->file = $fileName;	
		}
		$oanswer->save();
		
		$oticket = Oticket::findOrFail($oanswer->oticket_id);
		$oticket->updated_at = date('Y-m-d H:i:s');
		$oticket->updated_by_login = $user->user_login;
		$oticket->save();
		
		//Mandar notificacion a suscriber
		$role = getUserRole($user->ID);
		 
		if(($role == "administrator" ) || ($role == "contributor")){
			 
			//$view = View::make('emails.ticket_answered');
			$header_image = $dashboard_option->get_meta_value("dashboard_url") . "options/" . $dashboard_option->get_meta_image("email_header_image");
			$show_more_link = $dashboard_option->get_meta_value("dashboard_url") . "otickets/" . $oticket->id;
			
			Log::info('header_image: '. $header_image);
			Log::info('show_more_link: '. $show_more_link);
			
		 	$customer =  User::findOrFail($oticket->user_id);

resources/views/otickets/all.blade.php
@extends('layout')

@section('header')

<style>

	.list th {
	    background-color: #cecece;
	    text-align: left;
	    color: black;
	    padding: 0.4em 0.3em 0.4em 0.4em;
	    font-weight: 700;
	    font-size: 14px;
	}

</style>  
@endsection

@section('content')
			
<div class="row">
            <div class="col-md-12">

			
			<table class="table table-responsive list">
				<tbody><tr>
					<th colspan="6">All Tickets</th>
				</tr>

				<tr class="list_head">
					<td>TicketID</td>
					<td>Summary</td>
					<td>Regarding</td>
					<td>Status</td>
					<td nowrap="" align="right">Opened</td>
					<td nowrap="" align="right">Last Updated</td>
				</tr>

	
				  @foreach($otickets as $oticket)
		

					<tr class="list_entry" style="">
						<td><a href="/otickets/{{$oticket->id}}">{{$oticket->id}}</a></td>
						<td><a href="/otickets/{{$oticket->id}}">{{$oticket->summary}}</a></td>
						<td>
				
								{{$oticket->regarding}}<br>
				
						</td>
						<td>{{$oticket->status}}</td>
						<td nowrap="" align="right">
							{{$oticket->created_at}} <br>

							<span class="hint">
								
								<strong>{{$oticket->opened_by_login}}</strong>
							</span>
						</td>
						<td nowrap="" align="right">
							{{$oticket->updated_at}}<br>
							<span class="hint">
								
								<strong>{{$oticket->updated_by_login}}</strong>
							</span>
						</td>
					</tr>
	
				@endforeach


			</tbody></table>
			
			 {!! $otickets->render() !!}
				
		   </div>
</div>
   
@endsection

resources/views/otickets/create.blade.php
@extends('layout')

@section('header')

<style>

	.list th {
	    background-color: #cecece;
	    text-align: left;
	    color: black;
	    padding: 0.4em 0.3em 0.4em 0.4em;
	    font-weight: 700;
	    font-size: 14px;
	}
	
	.list {
	    width: 100%;
	    border-spacing: 5px;
	    border-collapse: collapse;
	    color: #333;
	    /* border: 1px solid #ccc; */
	    font-size: 14px;
	}
	
	input {
	    -webkit-appearance: textfield;
	    background-color: white;
	    -webkit-rtl-ordering: logical;
	    cursor: text;
	    padding: 1px;
	    border-width: 2px;
	    border-style: inset;
	    border-color: initial;
	    border-image: initial;
	}

</style>  
@endsection

@section('content')

 <form action="{{ route('otickets.store') }}" method="POST" enctype="multipart/form-data">
     <input type="hidden" name="_token" value="{{ csrf_token() }}">
	 

<table class="list">
	<tbody><tr>
		<th colspan="2">Open a Ticket</th>
	</tr>

	<tr class="list_entry">
		
		<td class="table_form_header">Summary</td>
		<td><br /> <input name="summary" id="summary" class="form-control" type="text" maxlength="64" size="40"> <br /></td>
	</tr>

	
		<tr class="list_entry">
			<td class="table_form_header">Regarding</td>
			<td>
				<select name="regarding" class="form-control">
					<option value="">Please make a selection</option>
					
					 @foreach($sites as $site)
					
						<option value="{{$site->domain}}">Pete: {{$site->domain}} </option>
						
					@endforeach
					
					<option value="Other">Other (general, billing, etc)</option>
					
					
				</select><br />
			</td>
		</tr>
	

	<tr class="list_entry">
		<td class="table_form_header">Description</td>
		<td>
			<textarea cols="100" class="form-control" rows="18" class="ticket_textarea" name="body" wrap="soft" maxlength="50000"></textarea><br />
		</td>
	</tr>
	<tr class="list_entry">
		<td></td>
		<td colspan="3">
			<input class="et_manage_submit" type="submit" value="Open Ticket">
		</td>
	</tr>
</tbody></table>

</form>

@endsection

resources/views/otickets/index.blade.php
@extends('layout')

@section('header')

<style>

	.list th {
	    background-color: #cecece;
	    text-align: left;
	    color: black;
	    padding: 0.4em 0.3em 0.4em 0.4em;
	    font-weight: 700;
	    font-size: 14px;
	}

</style>  
@endsection

@section('content')

	<div class="row">
		<div class="col-md-12">
			<h1>{{trans('dashboard.need_help')}}</h1>
		</div>
	</div>
			
<div class="row">
            <div class="col-md-12">

			
			<table class="table table-responsive list">
				<tbody><tr>
					<th colspan="6">Open Tickets</th>
				</tr>

				<tr class="list_head">
					<td>TicketID</td>
					<td>Summary</td>
					<td>Regarding</td>
					<td>Status</td>
					<td nowrap="" align="right">Opened</td>
					<td nowrap="" align="right">Last Updated</td>
				</tr>

	
				  @foreach($open_tickets as $open_ticket)
		

					<tr class="list_entry" style="">
						<td><a href="/otickets/{{$open_ticket->id}}">{{$open_ticket->id}}</a></td>
						<td><a href="/otickets/{{$open_ticket->id}}">{{$open_ticket->summary}}</a></td>
						<td>
				
								{{$open_ticket->regarding}}<br>
				
						</td>
						<td>{{$open_ticket->status}}</td>
						<td nowrap="" align="right">
							{{$open_ticket->created_at}} <br>

							<span class="hint">
								
								<strong>{{$open_ticket->opened_by_login}}</strong>
							</span>
						</td>
						<td nowrap="" align="right">
							{{$open_ticket->updated_at}}<br>
							<span class="hint">
								
								<strong>{{$open_ticket->updated_by_login}}</strong>
							</span>
						</td>
					</tr>
	
				@endforeach

				<tr class="list_entry" style="border-bottom-width: 0px">
					<td colspan="6" align="right"><a href="/otickets/create">Open a new Support Ticket</a></td>
				</tr>



				<tr colspan="6">
					<td>&nbsp;</td>
				</tr>



				<tr>
					<th colspan="6">Recently Closed Tickets</th>
				</tr>

				<tr class="list_head">
					<td>TicketID</td>
					<td>Summary</td>
					<td>Regarding</td>
					<td>Status</td>
					<td nowrap="" align="right">Opened</td>
					<td nowrap="" align="right">Last Updated</td>
				</tr>

	
		

					  @foreach($closed_tickets as $closed_ticket)
		

						<tr class="list_entry" style="">
							<td><a href="/otickets/{{$closed_ticket->id}}">{{$closed_ticket->id}}</a></td>
							<td><a href="/otickets/{{$closed_ticket->id}}">{{$closed_ticket->summary}}</a></td>
							<td>
				
									{{$closed_ticket->regarding}}<br>
				
							</td>
							<td>{{$closed_ticket->status}}</td>
							<td nowrap="" align="right">
								{{$closed_ticket->created_at}} <br>

								<span class="hint">
									 <strong>{{$closed_ticket->opened_by_login}}</strong>
								</span>
							</td>
							<td nowrap="" align="right">
								{{$closed_ticket->updated_at}}<br>
								
								<span class="hint">
								
									<strong>{{$closed_ticket->updated_by_login}}</strong>
								</span>
								
							</td>
						</tr>
	
					@endforeach
	

				<tr class="list_entry">
					<td colspan="6" align="right"><a href="/all_tickets">Show all tickets</a></td>
				</tr>

			</tbody></table>
			
				
		   </div>
</div>
   
@endsection

resources/views/otickets/open_tickets.blade.php
@extends('layout')

@section('header')

<style>

	.list th {
	    background-color: #cecece;
	    text-align: left;
	    color: black;
	    padding: 0.4em 0.3em 0.4em 0.4em;
	    font-weight: 700;
	    font-size: 14px;
	}

</style>  
@endsection

@section('content')
			
<div class="row">
            <div class="col-md-12">

			
			<table class="table table-responsive list">
				<tbody><tr>
					<th colspan="6">All Tickets</th>
				</tr>

				<tr class="list_head">
					<td>TicketID</td>
					<td>Summary</td>
					<td>Regarding</td>
					<td>Status</td>
					<td nowrap="" align="right">Opened</td>
					<td nowrap="" align="right">Last Updated</td>
				</tr>

	
				  @foreach($otickets as $oticket)
		

					<tr class="list_entry" style="">
						<td><a href="/otickets/{{$oticket->id}}">{{$oticket->id}}</a></td>
						<td><a href="/otickets/{{$oticket->id}}">{{$oticket->summary}}</a></td>
						<td>
				
								{{$oticket->regarding}}<br>
				
						</td>
						<td>{{$oticket->status}}</td>
						<td nowrap="" align="right">
							{{$oticket->created_at}} <br>

							<span class="hint">
								
								<strong>{{$oticket->opened_by_login}}</strong>
							</span>
						</td>
						<td nowrap="" align="right">
							{{$oticket->updated_at}}<br>
							<span class="hint">
								
								<strong>{{$oticket->updated_by_login}}</strong>
							</span>
						</td>
					</tr>
	
				@endforeach


			</tbody></table>
			
			 {!! $otickets->render() !!}
				
		   </div>
</div>
   
@endsection

resources/views/otickets/show.blade.php
@extends('layout')

@section('header')

<style>

	.list th {
	    background-color: #cecece;
	    text-align: left;
	    color: black;
	    padding: 0.4em 0.3em 0.4em 0.4em;
	    font-weight: 700;
	    font-size: 14px;
	}
	
	.package-table tbody tr:nth-child(odd){background:#FAFAFA;}
	.package-table td{border-top:0px !important; border-right:1px solid #fff !important;}
	.package-table tbody tr:nth-child(even){background:#DFDFDF; }

</style>  
@endsection

@section('content')

<div class="row">
            <div class="col-md-12">
			
			@if(($role== "administrator") || ($role == "contributor"))
			
			<select id ="oticket_sw">
			  
			  <option @if($oticket->status == "OPEN") selected="selected" @endif value="OPEN">OPEN</option>
			  <option @if($oticket->status == "CLOSED") selected="selected" @endif value="CLOSED">CLOSED</option>
			  
			</select>
			
			<br />
			
			@endif
	
<table class="table package-table">
	<tbody><tr>
		<th colspan="5">{{$oticket->id}} {{$oticket->summary}}</th>
	</tr>

	<tr class="list_head">
		<td>Status</td>
		<td nowrap="">Opened</td>
		<td nowrap="">Last Updated</td>
		<td nowrap="">Closed On</td>
		<td nowrap="">Regarding</td>
	</tr>

	<tr>
		<td>{{$oticket->status}}</td>
		<td>
			
			{{$oticket->created_at}}
			by <strong>{{$oticket->opened_by_login}}</strong>
		</td>
		<td>
			
			{{$oticket->updated_at}}
			by <strong>{{$oticket->updated_by_login}}</strong>
		</td>
		<td>
			@if($oticket->closed_at)
			{{$oticket->closed_at}}
			by <strong>{{$oticket->closed_at_login}}</strong>
			@endif
		</td>
		<td>
			
				{{$oticket->regarding}}<br>
			
		</td>
	</tr>
	
</tbody></table>
   
   
   <table class="table package-table">
   	<tbody><tr class="list_head">
   		<td colspan="5">&nbsp;</td>
   	</tr>

	

   		<tr class="list_entry">
   			<td class="support_left" valign="top">
   				
   				<strong>{{$oticket->opened_by_login}}</strong>
   				<br>
   				{{$oticket->created_at}}
   			</td>
   			<td colspan="4" class="ticketDescription" style=" ">{{$oticket->body}}</td>
   		</tr>
		
		 @foreach($oanswers as $oanswer)
	
   		<tr class="list_entry_alt">
   			<td class="col-md-3" valign="top">
   				
   				<strong>{{$oanswer->user_login}}</strong>
			
   				<br>
				
   				{{$oanswer->created_at}}
   			</td>
   			<td colspan="4" class="col-md-9">
   				{{$oanswer->body}}
				
				<br />
				@if($oanswer->file)
					
					<a href="/dashboard_tickets/{{$oticket->id}}/{{$oanswer->file}}">{{$oanswer->file}}</a>
					
				@endif
   			</td>
   		</tr>
		
		@endforeach
	
   		<tr class="list_entry">
   			<td class="col-md-3">
   				Add an Update<br>
   				<span class="hint">Update text required.
   			</span></td>
   			<td class="col-md-3">
				<form action="/store_answer" method="post"  enctype="multipart/form-data">
					
				<input type="hidden" id="_token" name="_token" value="{{csrf_token()}}">
				<input type="hidden" id="oticket_id" name="oticket_id" value="{{$oticket->id}}">
   				<textarea cols="65" rows="12" name="body" maxlength="50000"></textarea>
				
   				<br />
				
	            <div class="form-group">
	              <label>File</label>
                  <input type="file" id="filem" name="filem">
	            </div>
				
				<br />
				
   				<input class="et_manage_submit" type="submit" value="Add Update">
			
				</form>
				
   			</td>
   		</tr>

   </tbody></table>
   
							   
</div>
</div>   

<script>
	
	$( document ).ready(function() {
	  
		$( "#oticket_sw" ).change(function() {
		  
			jQuery.ajax({
				url: "/update_status",
				type: 'post',
				dataType: 'json',
				data: {oticket_id : {{$oticket->id}}, value: $(this).val(), _token: "{{csrf_token()}}"},
				success: function(data){
					
	  			 location.reload();
					
				}
			});
		  
		});
	  
	});
	
</script>


   
@endsection