app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//API validation routes no login required
Route::get('/validate_site_json', 'OapiController@validate_site_json');
Route::get('/validate_update_json', 'OapiController@validate_update_json');

//Dashboard routes
Route::get("/my_subscriptions","DashboardController@my_subscriptions");
Route::get("/my_plans","DashboardController@my_plans");
Route::get("/create_site","DashboardController@create_site");
Route::get("/my_sites","DashboardController@my_sites");
Route::get("/my_servers","DashboardController@my_servers");


Route::post("/create_linode","DashboardController@create_linode");
Route::post("/create_websitebar","DashboardController@create_websitebar");
Route::post("/delete_websitebar","DashboardController@delete_websitebar");
Route::post("/create_api_key","DashboardController@create_api_key");
Route::get('/logout', 'DashboardController@logout');
Route::post("/set_lang","DashboardController@set_lang");
Route::get("/addons","DashboardController@addons");
Route::get("/backups","DashboardController@backups");
Route::get("/restore","DashboardController@restore");
Route::get("/my_domains","DashboardController@my_domains");
Route::post("/publish_website","DashboardController@publish_website");
Route::post("/get_barserver_info","DashboardController@get_barserver_info");
Route::get("/save_barsite_from_pete","DashboardController@save_barsite_from_pete");
Route::get("/show_wp_pass","DashboardController@show_wp_pass");
Route::get("/check_websitebar_subdomain","DashboardController@check_websitebar_subdomain");
Route::get("/testui","DashboardController@testui");
Route::get("/save_barsite","DashboardController@save_barsite");

Route::get("/get_domains","DashboardController@get_domains");
Route::get("/shut_down","DashboardController@shut_down");
Route::get("/boot","DashboardController@boot");
Route::get("/reboot","DashboardController@reboot");

Route::get("/clone_barsite","DashboardController@clone_barsite");
Route::get("/delete_barsite","DashboardController@delete_barsite");
Route::get("/restore_barsite","DashboardController@restore_barsite");
Route::get("/destroy_barsite","DashboardController@destroy_barsite");
Route::get("/continue_barsite","DashboardController@continue_barsite");
Route::get("/suspend_barsite","DashboardController@suspend_barsite");
Route::get("/restore_barsite_from_backup","DashboardController@restore_barsite_from_backup");
Route::get("/publish_barsite","DashboardController@publish_barsite");
Route::get("/create_barsite","DashboardController@create_barsite");
Route::get("/my_addons","DashboardController@my_addons");

/////OMISSIONS ROUTES///////////

Route::get("/set_omission","OmissionsController@set_omission");
Route::get("/edit/{id}","OmissionsController@edit");
Route::post('/answer_test', 'OmissionsController@answer_test');
Route::post('/mission_submitted', 'OmissionsController@mission_submitted');
Route::post('/wp_select_user', 'OmissionsController@wp_select_user');
Route::post('/save_omission_file', 'OmissionsController@save_omission_file');
Route::post('/save_brief', 'OmissionsController@save_brief');
Route::get("/send_notification_test/{id}","OmissionsController@send_notification_test");

/////END OMISSIONS ROUTES///////

//Contributor routes
Route::get('/select_customer', 'ContributorsController@select_customer');

//Admin routes
Route::get('/open_tickets', 'AdminController@open_tickets');
Route::get('/customers', 'AdminController@customers');
Route::get('/get_customer/{id}', 'AdminController@get_customer');
Route::get('/test_email', 'AdminController@test_email');

//Otickets routes
Route::resource("otickets","OticketController");
Route::post("store_answer","OticketController@store_answer");
Route::post("update_status","OticketController@update_status");
Route::get("all_tickets","OticketController@all");

//Options routes
Route::resource("wp_global_options","WpGlobalOptionController");
Route::resource("barthemes","BarthemeController");
Route::resource("barrecords","BarrecordController");

Route::resource("bardomains","BardomainController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::get("/create_record","BardomainController@create_record");
Route::post("/store_record","BardomainController@store_record");
Route::post("/delete_record","BardomainController@delete_record");


Route::get('/', array('as' => 'dashboard.create_site', 'uses' => 'DashboardController@create_site'));

app/WpGlobalOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WpGlobalOption extends Model
{
    //
}

app/Http/Controllers/WpGlobalOptionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\WpGlobalOption;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Log;
use Illuminate\Support\Facades\Auth;
use App\DashboardOption;
use App;

class WpGlobalOptionController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	    {
	        $this->middleware('auth.wp');		
 			$this->middleware('auth.admin');
			
	    }
	
	public function index()
	{
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$wp_global_options = WpGlobalOption::orderBy('id', 'desc')->paginate(10);
		$viewsw = "options";
		
		return view('wp_global_options.index', compact('wp_global_options','viewsw','current_user','wordpress_url','dashboard_option','role','global_lang'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$viewsw = "options";
		return view('wp_global_options.create',compact('viewsw','current_user','wordpress_url','dashboard_option','role','global_lang'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$wp_global_option = new WpGlobalOption();

		$wp_global_option->option_name = $request->input("option_name");
        $wp_global_option->option_value = $request->input("option_value");
        $wp_global_option->image = $request->input("image");
		
		if($request->file('image')!= ""){
			Log::info('Entro en logica archivo');
				
			$file = $request->file('image');
	        // SET UPLOAD PATH
	        $destinationPath = 'options';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$wp_global_option->image = $fileName;
			
		}

		$wp_global_option->save();

		return redirect()->route('wp_global_options.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$wp_global_option = WpGlobalOption::findOrFail($id);

		return view('wp_global_options.show', compact('wp_global_option'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//////SHARED HTML VARIABLES///
	    $current_user = Auth::user();			
	    $wordpress_url = env('WP_URL');
	    $dashboard_option = new DashboardOption();
		$role = getUserRole($current_user->ID);
		if($current_user->dashboard_lang){
			$global_lang = $current_user->dashboard_lang;
			App::setLocale($current_user->dashboard_lang);
		}else{
			$global_lang = "en";
			App::setLocale("en");
		}
		//////////////////////////
		
		$viewsw = "options";
		$wp_global_option = WpGlobalOption::findOrFail($id);

		return view('wp_global_options.edit', compact('wp_global_option','viewsw','current_user','wordpress_url','dashboard_option','role','global_lang'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$wp_global_option = WpGlobalOption::findOrFail($id);

		$wp_global_option->option_name = $request->input("option_name");
        $wp_global_option->option_value = $request->input("option_value");
        $wp_global_option->image = $request->input("image");
		
		
		if($request->file('image')!= ""){
			Log::info('Entro en logica archivo');
				
			$file = $request->file('image');
	        // SET UPLOAD PATH
	        $destinationPath = 'options';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$wp_global_option->image = $fileName;
			
		}

		$wp_global_option->save();
		
		return Redirect::to("/wp_global_options");
		
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$wp_global_option = WpGlobalOption::findOrFail($id);
		$wp_global_option->delete();

		return redirect()->route('wp_global_options.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/wp_global_options/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3> Options / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">
			
            <form action="{{ route('wp_global_options.store') }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('meta_key')) has-error @endif">
                       <label for="meta_key-field">Option name</label>
                    <input type="text" id="option_name-field" name="option_name" class="form-control" value="{{ old("option_name") }}"/>
                      
                    </div>
                    <div class="form-group @if($errors->has('meta_value')) has-error @endif">
                       <label for="meta_value-field">Option value</label>
                    <textarea class="form-control" id="option_value-field" rows="3" name="option_value">{{ old("option_value") }}</textarea>
                       
                    </div>
					
						
		            <div class="form-group">
		              <label for="zip_file_url-field">Image</label>
	                  <input type="file" id="image" name="image">
		            </div>
				
				 	
					
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
					 <a class="btn btn-link pull-right" href="{{ route('wp_global_options.index') }}">Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_global_options/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3> WpGlobalOptions / Edit #{{$wp_global_option->id}}</h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_global_options.update', $wp_global_option->id) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
				
				
                <div class="form-group @if($errors->has('meta_key')) has-error @endif">
                       <label for="meta_key-field">Option name</label>
                    <input type="text" id="option_name-field" name="option_name" class="form-control" value="{{$wp_global_option->option_name}}"/>
                      
                    </div>
                    <div class="form-group @if($errors->has('meta_value')) has-error @endif">
                       <label for="meta_value-field">Option value</label>
                    <textarea class="form-control" id="option_value-field" rows="3" name="option_value">{{$wp_global_option->option_value}}</textarea>
                       
                    </div>
					
					@if($wp_global_option->image)
						<img class="img-responsive" src="/options/{{$wp_global_option->image}}">
					@endif
						
		            <div class="form-group">
		              <label for="zip_file_url-field">Image</label>
	                  <input type="file" id="image" name="image">
		            </div>
				
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('wp_global_options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_global_options/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h3>
            Options
            <a class="btn btn-success pull-right" href="{{ route('wp_global_options.create') }}">Create</a>
        </h3>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($wp_global_options->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Option name</th>
							<th>Option value</th>
							<th>Option image</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($wp_global_options as $wp_global_option)
                            <tr>
                                <td>{{$wp_global_option->id}}</td>
                                <td>{{$wp_global_option->option_name}}</td>
								<td>{{$wp_global_option->option_value}}</td>
								<td>
									@if($wp_global_option->image)
										<img class="img-responsive" src="/options/{{$wp_global_option->image}}">
									@endif
								
								</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('wp_global_options.show', $wp_global_option->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('wp_global_options.edit', $wp_global_option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('wp_global_options.destroy', $wp_global_option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $wp_global_options->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/wp_global_options/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>WpGlobalOptions / Show #{{$wp_global_option->id}}</h1>
        <form action="{{ route('wp_global_options.destroy', $wp_global_option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('wp_global_options.edit', $wp_global_option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                
            </form>

            <a class="btn btn-link" href="{{ route('wp_global_options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection